-- ============================================================
-- Campaign suggestions (Campaigns overhaul Phase 4 — the AI learning loop)
-- ----------------------------------------------------------------
-- Phase 2's analyze-campaign action (playbook-ai) already reads one
-- campaign's metrics and writes a plain-English analysis to
-- campaigns.analysis_json. This migration adds the structured, actionable
-- half of that loop: a queue of AI-proposed TEMPLATE edits (subject/body/
-- timing/audience copy changes), each grounded in the numbers from a
-- specific campaign, that an admin reviews and applies or dismisses from
-- the new Insights panel.
--
-- One row = one proposed change to one campaign_template, sourced from one
-- campaign's performance (campaign_id is the "why", template_id is the
-- "what gets edited"). campaign_id is nullable (on delete set null) so a
-- suggestion's provenance survives that source campaign being deleted;
-- template_id is NOT NULL (on delete cascade) because a suggestion with no
-- template to apply to is meaningless — see the campaign-insights action
-- in supabase/functions/playbook-ai/index.ts, which only ever inserts a row
-- when the source campaign has a template_id.
--
-- RLS mirrors campaign_events (20260722180000): admin-only SELECT, no
-- INSERT/UPDATE/DELETE policy for `authenticated` at all. Suggestions are
-- written by playbook-ai's service-role client; status transitions
-- (pending -> applied/dismissed) go through playbook-smartlead's new
-- `decide-suggestion` action, same "table is read-only for the client,
-- edge function does the write" shape as mark-reply-handled.
--
-- Idempotent (create table/index if not exists); additive only.
-- To reverse: drop the table and its RLS policy — nothing else in the
-- schema references it yet.
-- ============================================================

begin;

create table if not exists public.campaign_suggestions (
  id             uuid primary key default gen_random_uuid(),
  campaign_id    uuid references public.campaigns(id) on delete set null,
  template_id    uuid not null references public.campaign_templates(id) on delete cascade,
  step_order     int,
  kind           text not null check (kind in ('subject','body','timing','audience','general')),
  current_value  text,
  suggested_value text,
  rationale      text not null,
  status         text not null default 'pending' check (status in ('pending','applied','dismissed')),
  created_at     timestamptz not null default now(),
  decided_at     timestamptz,
  decided_by     uuid references public.user_profiles(id) on delete set null
);

comment on table public.campaign_suggestions is
  'AI-proposed edits to a campaign_template (subject/body/timing/audience copy), generated by playbook-ai''s campaign-insights action from one source campaign''s real performance data. Reviewed from the Insights panel (InsightsPanel.tsx); applying edits the TEMPLATE only — running campaigns are never touched. Written by the service-role client only (see RLS below); status transitions go through playbook-smartlead''s decide-suggestion action.';
comment on column public.campaign_suggestions.campaign_id is
  'The campaign whose metrics/events grounded this suggestion. Nullable (on delete set null) so the suggestion''s history survives that campaign being deleted later.';
comment on column public.campaign_suggestions.template_id is
  'The campaign_template this suggestion proposes editing. NOT NULL — campaign-insights only inserts a row when the source campaign has a template_id; a templateless (one-off) campaign yields zero suggestion rows even if the AI would otherwise have ideas.';
comment on column public.campaign_suggestions.step_order is
  'The step''s `order` field (see SequenceStep in src/features/playbook/types.ts) within template.steps this suggestion targets, or null for a template-wide/general suggestion (kind=''general'' or an audience-level note).';
comment on column public.campaign_suggestions.current_value is
  'The current value being proposed for replacement (e.g. the step''s existing subject_template), for a stacked/side-by-side before-after in the UI. Null when there is no single current value to diff against (e.g. kind=''general'').';
comment on column public.campaign_suggestions.suggested_value is
  'The AI''s proposed replacement value. For kind=''timing'', this is only actionable by the Apply button when it parses cleanly as a day_offset/send_window change (see applySuggestionToTemplate in src/features/playbook/api.ts) — otherwise Apply is disabled with a "needs a manual edit" tooltip.';
comment on column public.campaign_suggestions.decided_by is
  'The admin who applied or dismissed this suggestion. Null for a suggestion still pending, or if the deciding user was later deleted.';

create index if not exists idx_campaign_suggestions_template_status
  on public.campaign_suggestions (template_id, status);
create index if not exists idx_campaign_suggestions_campaign
  on public.campaign_suggestions (campaign_id);

alter table public.campaign_suggestions enable row level security;

-- Admin-only read. No insert/update/delete policy for `authenticated` at
-- all — the service-role client (playbook-ai's campaign-insights action,
-- and playbook-smartlead's decide-suggestion action for status updates)
-- bypasses RLS the same way every other svc.from(...) write in this schema
-- does, so client-side writes are structurally impossible rather than
-- merely policy-denied.
drop policy if exists "campaign_suggestions_read_admin" on public.campaign_suggestions;
create policy "campaign_suggestions_read_admin"
  on public.campaign_suggestions
  for select
  to authenticated
  using ((select public.is_admin()));

commit;

notify pgrst, 'reload schema';
