-- The Daily Deal — weekday word-guessing mini-game (Nathan, 2026-07-31).
--
-- Wordle-style: one shared 5-letter word per WEEKDAY (Pacific time), 6
-- guesses, weekly leaderboard, weekend recap. Design decisions of record:
--   * Answers live ONLY server-side (these tables are service-role-only; the
--     daily-deal edge fn evaluates guesses) — view-source reveals nothing.
--   * A word is BURNED (used_on set) only when someone actually guesses that
--     day. A zero-play day releases its word back to the pool (Nathan's
--     low-traction rule), and the recap never reveals unburned words.
--   * Pool exhaustion fail-safe: recycle the 100 oldest-used words rather
--     than ever failing to pick.
--   * Rich per-player history kept forever (guesses, times, points, streaks)
--     for the someday-arcade — deliberately more than the other games' PB+top5.
--
-- RLS: enabled, NO authenticated policies — same service-role-only engine
-- convention as campaign_events (all access via the daily-deal edge fn).

create table public.daily_deal_words (
  id uuid primary key default gen_random_uuid(),
  word text not null unique check (word ~ '^[a-z]{5}$'),
  used_on date,
  recycled_count integer not null default 0
);

create table public.daily_deal_puzzles (
  puzzle_date date primary key,
  word_id uuid not null references public.daily_deal_words(id),
  created_at timestamptz not null default now()
);

create table public.daily_deal_results (
  user_id uuid not null references auth.users(id) on delete cascade,
  puzzle_date date not null references public.daily_deal_puzzles(puzzle_date) on delete cascade,
  guesses jsonb not null default '[]'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  won boolean,
  ms_elapsed integer,
  points integer,
  streak_after integer,
  primary key (user_id, puzzle_date)
);

alter table public.daily_deal_words enable row level security;
alter table public.daily_deal_puzzles enable row level security;
alter table public.daily_deal_results enable row level security;

-- Atomic daily pick (advisory-locked so two simultaneous first-openers can't
-- double-pick). Releases zero-play words from past days first, then picks a
-- random unused word for p_date, inserting the puzzle row. Returns the word
-- (service-role caller only — clients never call this).
create or replace function public.daily_deal_ensure_puzzle(p_date date)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_word text;
  v_word_id uuid;
begin
  perform pg_advisory_xact_lock(hashtext('daily-deal-pick'));

  -- Existing puzzle → return its word.
  select w.word into v_word
    from daily_deal_puzzles p join daily_deal_words w on w.id = p.word_id
   where p.puzzle_date = p_date;
  if found then return v_word; end if;

  -- Nathan's low-traction rule: past puzzle days where nobody made a single
  -- guess release their word back to the pool and drop the puzzle row.
  update daily_deal_words w
     set used_on = null, recycled_count = recycled_count + 1
   where w.id in (
     select p.word_id from daily_deal_puzzles p
      where p.puzzle_date < p_date
        and not exists (
          select 1 from daily_deal_results r
           where r.puzzle_date = p.puzzle_date
             and jsonb_array_length(r.guesses) > 0
        )
   );
  delete from daily_deal_puzzles p
   where p.puzzle_date < p_date
     and not exists (
       select 1 from daily_deal_results r
        where r.puzzle_date = p.puzzle_date
          and jsonb_array_length(r.guesses) > 0
     );

  -- Exhaustion fail-safe: if nothing is unused, recycle the 100 oldest.
  if not exists (select 1 from daily_deal_words where used_on is null) then
    update daily_deal_words
       set used_on = null, recycled_count = recycled_count + 1
     where id in (
       select id from daily_deal_words order by used_on asc limit 100
     );
  end if;

  select id, word into v_word_id, v_word
    from daily_deal_words
   where used_on is null
   order by random()
   limit 1;

  insert into daily_deal_puzzles (puzzle_date, word_id) values (p_date, v_word_id);
  return v_word;
end;
$$;

revoke all on function public.daily_deal_ensure_puzzle(date) from public, anon, authenticated;

insert into public.daily_deal_words (word) values
  ('quota'),
  ('pitch'),
  ('churn'),
  ('close'),
  ('deals'),
  ('leads'),
  ('notes'),
  ('tasks'),
  ('email'),
  ('phone'),
  ('brand'),
  ('price'),
  ('offer'),
  ('sales'),
  ('terms'),
  ('quote'),
  ('agent'),
  ('buyer'),
  ('owner'),
  ('staff'),
  ('badge'),
  ('chart'),
  ('month'),
  ('weeks'),
  ('daily'),
  ('first'),
  ('final'),
  ('prize'),
  ('score'),
  ('bonus'),
  ('about'),
  ('above'),
  ('actor'),
  ('adopt'),
  ('after'),
  ('again'),
  ('agree'),
  ('ahead'),
  ('alarm'),
  ('album'),
  ('alert'),
  ('alike'),
  ('alive'),
  ('allow'),
  ('alone'),
  ('along'),
  ('alter'),
  ('among'),
  ('angle'),
  ('angry'),
  ('ankle'),
  ('apart'),
  ('apple'),
  ('apply'),
  ('arena'),
  ('argue'),
  ('arise'),
  ('armor'),
  ('aroma'),
  ('array'),
  ('arrow'),
  ('aside'),
  ('asset'),
  ('audio'),
  ('audit'),
  ('avoid'),
  ('awake'),
  ('award'),
  ('aware'),
  ('badly'),
  ('baker'),
  ('basic'),
  ('batch'),
  ('beach'),
  ('beard'),
  ('beast'),
  ('begin'),
  ('being'),
  ('belly'),
  ('bench'),
  ('berry'),
  ('birth'),
  ('black'),
  ('blade'),
  ('blame'),
  ('blank'),
  ('blast'),
  ('blaze'),
  ('bleed'),
  ('blend'),
  ('bless'),
  ('blind'),
  ('block'),
  ('bloom'),
  ('board'),
  ('boast'),
  ('boost'),
  ('booth'),
  ('bound'),
  ('brain'),
  ('brake'),
  ('brave'),
  ('bread'),
  ('break'),
  ('breed'),
  ('brick'),
  ('bride'),
  ('brief'),
  ('bring'),
  ('broad'),
  ('broke'),
  ('brook'),
  ('broom'),
  ('brown'),
  ('brush'),
  ('build'),
  ('built'),
  ('bunch'),
  ('burst'),
  ('cabin'),
  ('cable'),
  ('candy'),
  ('cargo'),
  ('carry'),
  ('catch'),
  ('cause'),
  ('cedar'),
  ('chain'),
  ('chair'),
  ('chalk'),
  ('charm'),
  ('chase'),
  ('cheap'),
  ('check'),
  ('cheek'),
  ('cheer'),
  ('chess'),
  ('chest'),
  ('chief'),
  ('child'),
  ('chill'),
  ('choir'),
  ('chose'),
  ('civic'),
  ('civil'),
  ('claim'),
  ('clash'),
  ('clasp'),
  ('clean'),
  ('clear'),
  ('clerk'),
  ('click'),
  ('cliff'),
  ('climb'),
  ('clock'),
  ('cloth'),
  ('cloud'),
  ('coach'),
  ('coast'),
  ('cocoa'),
  ('color'),
  ('comet'),
  ('comic'),
  ('coral'),
  ('couch'),
  ('could'),
  ('count'),
  ('court'),
  ('cover'),
  ('crack'),
  ('craft'),
  ('crane'),
  ('crash'),
  ('crawl'),
  ('crazy'),
  ('cream'),
  ('creek'),
  ('crest'),
  ('crime'),
  ('crisp'),
  ('cross'),
  ('crowd'),
  ('crown'),
  ('crumb'),
  ('crush'),
  ('curve'),
  ('cycle'),
  ('dairy'),
  ('dance'),
  ('dandy'),
  ('dealt'),
  ('debut'),
  ('decay'),
  ('decor'),
  ('delay'),
  ('dense'),
  ('depth'),
  ('diary'),
  ('dodge'),
  ('doing'),
  ('donor'),
  ('doubt'),
  ('dough'),
  ('dozen'),
  ('draft'),
  ('drain'),
  ('drama'),
  ('drank'),
  ('dream'),
  ('dress'),
  ('dried'),
  ('drift'),
  ('drill'),
  ('drink'),
  ('drive'),
  ('drove'),
  ('dusty'),
  ('dwell'),
  ('eager'),
  ('eagle'),
  ('early'),
  ('earth'),
  ('eight'),
  ('elbow'),
  ('elder'),
  ('elect'),
  ('elite'),
  ('empty'),
  ('enemy'),
  ('enjoy'),
  ('enter'),
  ('entry'),
  ('equal'),
  ('error'),
  ('essay'),
  ('event'),
  ('every'),
  ('exact'),
  ('exist'),
  ('extra'),
  ('fable'),
  ('faint'),
  ('fairy'),
  ('faith'),
  ('false'),
  ('fancy'),
  ('fatal'),
  ('fault'),
  ('favor'),
  ('feast'),
  ('fence'),
  ('ferry'),
  ('fever'),
  ('fiber'),
  ('field'),
  ('fifty'),
  ('fight'),
  ('filed'),
  ('fills'),
  ('fined'),
  ('fifth'),
  ('flame'),
  ('flash'),
  ('fleet'),
  ('flesh'),
  ('float'),
  ('flock'),
  ('flood'),
  ('floor'),
  ('flour'),
  ('fluid'),
  ('flute'),
  ('focus'),
  ('foggy'),
  ('force'),
  ('forge'),
  ('forth'),
  ('forty'),
  ('forum'),
  ('found'),
  ('frame'),
  ('frank'),
  ('fraud'),
  ('fresh'),
  ('front'),
  ('frost'),
  ('fruit'),
  ('fudge'),
  ('fully'),
  ('funny'),
  ('gauge'),
  ('ghost'),
  ('giant'),
  ('given'),
  ('giver'),
  ('glass'),
  ('gleam'),
  ('glide'),
  ('globe'),
  ('glory'),
  ('glove'),
  ('going'),
  ('goose'),
  ('grace'),
  ('grade'),
  ('grain'),
  ('grand'),
  ('grant'),
  ('grape'),
  ('grasp'),
  ('grass'),
  ('grave'),
  ('great'),
  ('green'),
  ('greet'),
  ('grief'),
  ('grill'),
  ('grind'),
  ('groan'),
  ('groom'),
  ('group'),
  ('grove'),
  ('grown'),
  ('guard'),
  ('guess'),
  ('guest'),
  ('guide'),
  ('habit'),
  ('happy'),
  ('hardy'),
  ('haste'),
  ('hatch'),
  ('haven'),
  ('heard'),
  ('heart'),
  ('heavy'),
  ('hedge'),
  ('hello'),
  ('hence'),
  ('hilly'),
  ('hinge'),
  ('hobby'),
  ('honey'),
  ('honor'),
  ('horse'),
  ('hotel'),
  ('hound'),
  ('house'),
  ('human'),
  ('humor'),
  ('hurry'),
  ('ideal'),
  ('image'),
  ('imply'),
  ('index'),
  ('inner'),
  ('input'),
  ('irony'),
  ('issue'),
  ('ivory'),
  ('jelly'),
  ('jewel'),
  ('joint'),
  ('jolly'),
  ('judge'),
  ('juice'),
  ('juicy'),
  ('kneel'),
  ('knife'),
  ('knock'),
  ('known'),
  ('label'),
  ('labor'),
  ('large'),
  ('laser'),
  ('latch'),
  ('later'),
  ('laugh'),
  ('layer'),
  ('learn'),
  ('lease'),
  ('least'),
  ('leave'),
  ('ledge'),
  ('legal'),
  ('lemon'),
  ('level'),
  ('light'),
  ('limit'),
  ('linen'),
  ('liver'),
  ('lobby'),
  ('local'),
  ('lodge'),
  ('logic'),
  ('loose'),
  ('lorry'),
  ('loyal'),
  ('lucky'),
  ('lunar'),
  ('lunch'),
  ('lying'),
  ('magic'),
  ('major'),
  ('maker'),
  ('maple'),
  ('march'),
  ('match'),
  ('maybe'),
  ('mayor'),
  ('meant'),
  ('medal'),
  ('media'),
  ('mercy'),
  ('merge'),
  ('merit'),
  ('merry'),
  ('metal'),
  ('meter'),
  ('midst'),
  ('might'),
  ('minor'),
  ('minus'),
  ('mixed'),
  ('model'),
  ('moist'),
  ('money'),
  ('moral'),
  ('motor'),
  ('mount'),
  ('mouse'),
  ('mouth'),
  ('movie'),
  ('music'),
  ('naval'),
  ('nerve'),
  ('never'),
  ('newly'),
  ('night'),
  ('noble'),
  ('noise'),
  ('north'),
  ('notch'),
  ('novel'),
  ('nurse'),
  ('oasis'),
  ('occur'),
  ('ocean'),
  ('often'),
  ('olive'),
  ('onion'),
  ('onset'),
  ('opera'),
  ('orbit'),
  ('order'),
  ('organ'),
  ('other'),
  ('ought'),
  ('ounce'),
  ('outer'),
  ('oxide'),
  ('ozone'),
  ('paint'),
  ('panel'),
  ('panic'),
  ('paper'),
  ('party'),
  ('pasta'),
  ('paste'),
  ('patch'),
  ('pause'),
  ('peace'),
  ('peach'),
  ('pearl'),
  ('pedal'),
  ('penny'),
  ('perch'),
  ('petal'),
  ('phase'),
  ('photo'),
  ('piano'),
  ('piece'),
  ('pilot'),
  ('pinch'),
  ('pixel'),
  ('pizza'),
  ('place'),
  ('plain'),
  ('plane'),
  ('plant'),
  ('plate'),
  ('plaza'),
  ('plead'),
  ('pluck'),
  ('plumb'),
  ('pours'),
  ('point'),
  ('polar'),
  ('porch'),
  ('pouch'),
  ('pound'),
  ('power'),
  ('press'),
  ('pride'),
  ('prime'),
  ('print'),
  ('prior'),
  ('probe'),
  ('promo'),
  ('proof'),
  ('proud'),
  ('prove'),
  ('prune'),
  ('pulse'),
  ('punch'),
  ('pupil'),
  ('puppy'),
  ('purse'),
  ('queen'),
  ('query'),
  ('quest'),
  ('queue'),
  ('quick'),
  ('quiet'),
  ('quilt'),
  ('quite'),
  ('radar'),
  ('radio'),
  ('raise'),
  ('rally'),
  ('ranch'),
  ('range'),
  ('rapid'),
  ('ratio'),
  ('reach'),
  ('react'),
  ('ready'),
  ('realm'),
  ('rebel'),
  ('refer'),
  ('reign'),
  ('relax'),
  ('relay'),
  ('renew'),
  ('reply'),
  ('reset'),
  ('resin'),
  ('retro'),
  ('rhyme'),
  ('rider'),
  ('ridge'),
  ('rifle'),
  ('right'),
  ('rigid'),
  ('rinse'),
  ('risky'),
  ('rival'),
  ('river'),
  ('roast'),
  ('robin'),
  ('robot'),
  ('rocky'),
  ('roost'),
  ('rough'),
  ('round'),
  ('route'),
  ('royal'),
  ('rugby'),
  ('ruler'),
  ('rumor'),
  ('rural'),
  ('rusty'),
  ('sadly'),
  ('salad'),
  ('salon'),
  ('salsa'),
  ('sandy'),
  ('sauce'),
  ('scale'),
  ('scarf'),
  ('scene'),
  ('scent'),
  ('scoop'),
  ('scope'),
  ('scout'),
  ('scrap'),
  ('seize'),
  ('sense'),
  ('serve'),
  ('seven'),
  ('shade'),
  ('shaft'),
  ('shake'),
  ('shall'),
  ('shape'),
  ('share'),
  ('sharp'),
  ('sheep'),
  ('sheet'),
  ('shelf'),
  ('shell'),
  ('shift'),
  ('shine'),
  ('shiny'),
  ('shirt'),
  ('shock'),
  ('shore'),
  ('short'),
  ('shout'),
  ('shown'),
  ('sight'),
  ('silly'),
  ('since'),
  ('siren'),
  ('sixty'),
  ('skill'),
  ('skirt'),
  ('slate'),
  ('sleek'),
  ('sleep'),
  ('slice'),
  ('slide'),
  ('slope'),
  ('small'),
  ('smart'),
  ('smile'),
  ('smoke'),
  ('snack'),
  ('snake'),
  ('sneak'),
  ('solar'),
  ('solid'),
  ('solve'),
  ('sorry'),
  ('sound'),
  ('south'),
  ('space'),
  ('spare'),
  ('spark'),
  ('speak'),
  ('speed'),
  ('spell'),
  ('spend'),
  ('spice'),
  ('spike'),
  ('spine'),
  ('spite'),
  ('split'),
  ('spoke'),
  ('spoon'),
  ('sport'),
  ('spray'),
  ('spree'),
  ('stack'),
  ('stage'),
  ('stair'),
  ('stake'),
  ('stamp'),
  ('stand'),
  ('stare'),
  ('start'),
  ('state'),
  ('steam'),
  ('steel'),
  ('steep'),
  ('steer'),
  ('stems'),
  ('stern'),
  ('stick'),
  ('stiff'),
  ('still'),
  ('sting'),
  ('stock'),
  ('stone'),
  ('stood'),
  ('store'),
  ('storm'),
  ('story'),
  ('stout'),
  ('stove'),
  ('strap'),
  ('straw'),
  ('strip'),
  ('stuck'),
  ('study'),
  ('stuff'),
  ('style'),
  ('sugar'),
  ('suite'),
  ('sunny'),
  ('super'),
  ('surge'),
  ('sweet'),
  ('swept'),
  ('swift'),
  ('swing'),
  ('sword'),
  ('syrup'),
  ('table'),
  ('taken'),
  ('taste'),
  ('teach'),
  ('tempo'),
  ('tenth'),
  ('thank'),
  ('theme'),
  ('there'),
  ('thick'),
  ('thing'),
  ('think'),
  ('third'),
  ('thorn'),
  ('those'),
  ('three'),
  ('threw'),
  ('throw'),
  ('thumb'),
  ('tiger'),
  ('tight'),
  ('timer'),
  ('title'),
  ('toast'),
  ('today'),
  ('token'),
  ('tooth'),
  ('topic'),
  ('torch'),
  ('total'),
  ('touch'),
  ('tough'),
  ('tower'),
  ('trace'),
  ('track'),
  ('trade'),
  ('trail'),
  ('train'),
  ('trait'),
  ('treat'),
  ('trend'),
  ('trial'),
  ('tribe'),
  ('trick'),
  ('tried'),
  ('troop'),
  ('truck'),
  ('truly'),
  ('trunk'),
  ('trust'),
  ('truth'),
  ('tulip'),
  ('tutor'),
  ('twice'),
  ('twist'),
  ('ultra'),
  ('uncle'),
  ('under'),
  ('union'),
  ('unite'),
  ('unity'),
  ('until'),
  ('upper'),
  ('upset'),
  ('urban'),
  ('usage'),
  ('usher'),
  ('usual'),
  ('valid'),
  ('value'),
  ('vapor'),
  ('vault'),
  ('venue'),
  ('verse'),
  ('video'),
  ('vigor'),
  ('vinyl'),
  ('visit'),
  ('vital'),
  ('vivid'),
  ('vocal'),
  ('voice'),
  ('voter'),
  ('wagon'),
  ('waist'),
  ('watch'),
  ('water'),
  ('weary'),
  ('weigh'),
  ('whale'),
  ('wheat'),
  ('wheel'),
  ('where'),
  ('which'),
  ('while'),
  ('white'),
  ('whole'),
  ('whose'),
  ('widen'),
  ('width'),
  ('wield'),
  ('windy'),
  ('wiser'),
  ('witty'),
  ('woman'),
  ('world'),
  ('worry'),
  ('worth'),
  ('would'),
  ('woven'),
  ('wrist'),
  ('write'),
  ('wrote'),
  ('yacht'),
  ('yeast'),
  ('yield'),
  ('young'),
  ('youth'),
  ('zebra')
on conflict (word) do nothing;
