-- Jordan Mayer's approved fixed-copy 8-Touch preset (Nathan, 2026-08-18).
-- The preset must open fully populated and must never ask AI to draft or adapt
-- its four email steps. Running campaigns remain frozen snapshots.

begin;

update public.campaign_templates
set steps = $steps$[
  {"order":1,"day_offset":1,"channel":"EMAIL_AUTO","weekday_target":"MON","send_window_start":"10:00","send_window_end":"11:00","automation":"AUTO","content_ai_draft":false,"pause_on_reply":true,"stop_on_unsubscribe":true,"subject_template":"Have you scheduled your 2026 Security Risk Analysis?","body_template":"<p>Hi {{first_name}},</p><p>I wanted to reach out about HIPAA compliance at {{company}}. Medcurity handles the Security Risk Analysis for healthcare organizations nationwide, and everything lives in one platform where your team can see where things stand and pull documentation when someone asks for it.</p><p>Could you point me to the person in charge of completing the Security Risk Assessment at {{company}}? I would appreciate it.</p><p>Thanks so much,<br>{{sender_name}}</p>"},
  {"order":2,"day_offset":5,"channel":"EMAIL_AUTO","weekday_target":"FRI","send_window_start":"10:00","send_window_end":"11:00","automation":"AUTO","content_ai_draft":false,"pause_on_reply":true,"stop_on_unsubscribe":true,"subject_template":"Re: Have you scheduled your 2026 Security Risk Analysis?","body_template":"<p>Hi {{first_name}},</p><p>Following up on my note from last week.</p><p>Not every organization wants to run the Security Risk Analysis in house. Our team can do the work for you, and your team gets a platform where the results, the documentation, and what is still open are all visible in one place.</p><p>Would it be helpful to see how another organization the size of {{company}} handles this? Happy to share what that looks like.</p><p>Thanks,<br>{{sender_name}}</p>"},
  {"order":3,"day_offset":8,"channel":"CALL","weekday_target":"MON","send_window_start":"10:00","send_window_end":"12:00","automation":"MANUAL","manual_task_title_template":"Call {{first_name}} @ {{company}}","manual_task_priority":"high","task_note_template":"First call attempt. Reference the Day 5 email.\n\nOpener: Hi {{first_name}}, this is {{sender_name}} with Medcurity. I sent you a note on Friday about your Security Risk Analysis. Do you have two minutes, or did I catch you at a bad time?\n\nFind out who owns the SRA, when it was last completed, when it is next due, and whether an audit, attestation, payer, or grant requirement puts a date on it. If the call goes anywhere, offer two specific meeting windows and send the invite while you are still on the phone.\n\nVoicemail: Hi {{first_name}}, this is {{sender_name}} with Medcurity. I sent you an email on Friday about your Security Risk Analysis. We handle the assessment for healthcare organizations and give your team one place to manage and view it. My number is {{phone}}. I will follow up by email as well. Thanks."},
  {"order":4,"day_offset":12,"channel":"LINKEDIN","weekday_target":"FRI","send_window_start":"09:00","send_window_end":"10:00","automation":"MANUAL","manual_task_title_template":"LinkedIn connect: {{first_name}}","manual_task_priority":"normal","task_note_template":"Send the connection request with no note. If there is a real personal reason to write, such as a shared connection or event, write your own note. Otherwise leave it empty."},
  {"order":5,"day_offset":15,"channel":"EMAIL_AUTO","weekday_target":"MON","send_window_start":"10:00","send_window_end":"11:00","automation":"AUTO","content_ai_draft":false,"pause_on_reply":true,"stop_on_unsubscribe":true,"subject_template":"Where the SRA lives at {{company}} once it is done","body_template":"<p>Hi {{first_name}},</p><p>One part of this that is easy to overlook:</p><p>When the Security Risk Analysis is finished, you still need somewhere to keep it, see what is still open, and find it quickly when someone asks. That is what our platform gives your team, whether we run the assessment for you or not.</p><p>Want me to send over a short look at how that works?</p><p>Thanks,<br>{{sender_name}}</p>"},
  {"order":6,"day_offset":19,"channel":"CALL","weekday_target":"FRI","send_window_start":"10:00","send_window_end":"12:00","automation":"MANUAL","manual_task_title_template":"Call {{first_name}} @ {{company}}","manual_task_priority":"high","task_note_template":"Second call attempt. Reference the LinkedIn connection or prior email opens when true.\n\nConnected opener: Hi {{first_name}}, this is {{sender_name}} with Medcurity. We connected on LinkedIn a week or so ago and I wanted to put a voice to the name. I have one quick question about how {{company}} handles its Security Risk Analysis. Is now a bad time?\n\nShort-call close: If I could send you one thing that would be useful on the SRA, what would it be?\n\nOffer two specific meeting windows before hanging up. If they name a renewal or audit date, schedule the Pulse follow-up two months ahead of it.\n\nVoicemail: Hi {{first_name}}, {{sender_name}} at Medcurity. Trying you once more about the Security Risk Analysis. If it is not a priority right now, reply to my email and tell me so, and I will stop reaching out. If it is, I would love fifteen minutes to show you what we would put in front of your team. My number is {{phone}}. Thanks."},
  {"order":7,"day_offset":23,"channel":"LINKEDIN","weekday_target":"TUE","send_window_start":"09:00","send_window_end":"10:00","automation":"MANUAL","manual_task_title_template":"LinkedIn message: {{first_name}}","manual_task_priority":"normal","task_note_template":"Only send if the Day 12 request was accepted. Message: Thanks for connecting, {{first_name}}. If the HIPAA risk assessment ever ends up on your list and you want a second set of eyes on it, I am happy to help. Either way, good to be connected.\n\nIf they did not accept, mark the task done and do not send a second request."},
  {"order":8,"day_offset":26,"channel":"EMAIL_AUTO","weekday_target":"FRI","send_window_start":"10:00","send_window_end":"11:00","automation":"AUTO","content_ai_draft":false,"pause_on_reply":true,"stop_on_unsubscribe":true,"subject_template":"Re: Where the SRA lives at {{company}} once it is done","body_template":"<p>Hi {{first_name}},</p><p>I have not heard back, so I will assume the timing is not right and leave it here.</p><p>If the Security Risk Analysis comes back around later this year, or you would like a second set of eyes on the one you already have, just reply to this email and I will help however I can.</p><p>Thanks for your time,<br>{{sender_name}}</p>"}
]$steps$::jsonb,
    updated_at = now()
where id = '11111111-0000-4000-a000-000000000001';

commit;

notify pgrst, 'reload schema';
